env:
  global:

language: java
sudo: false
install:
- cd react-frontend
- npm install
- cd ..
script:
- cd react-frontend
- npm run build
- cd ..
- mkdir -p backend/ts3socialai/src/main/resources/public
- cp -r ./react-frontend/build/* ./backend/ts3socialai/src/main/resources/public
- cd backend/ts3socialai
- mvn clean install -DskipTests
- cd ../tsas-common
- mvn clean install
- cd ../tsas-tsuds
- mvn clean install -DskipTests
- cd ../..
after_success:
- curl --ftp-create-dirs -T tsas-tsuds/target/tsuds.jar -u $FTP_USER:$FTP_PASSWORD ftp://gr-esports.de/
