language: java
sudo: false
cache:
  npm: false
install:
- cd react-frontend
- rm -rf node_modules
- npm install
- cd ..
script:
- cd react-frontend
- npm run build
- cd ..
- mkdir -p backend/ts3socialai/src/main/resources/public
- cp -r ./react-frontend/build/* ./backend/ts3socialai/src/main/resources/public
- cd backend/ts3socialai
- mvn clean install -DskipTests
- cd ../tsas-common
- mvn clean install
- cd ../tsas-tsuds
- mvn clean install -DskipTests
- cd ../tsas-tsurs
- mvn clean install -DskipTests
- cd ../tsas-tsups
- mvn clean install -DskipTests
- cd ../..
after_success:
- curl -T backend/tsas-tsuds/target/tsuds.jar -u $FTP_USER:$FTP_PASSWORD ftp://193.31.26.152
- curl -T backend/tsas-tsurs/target/tsurs.jar -u $FTP_USER:$FTP_PASSWORD ftp://193.31.26.152
- curl -T backend/tsas-tsups/target/tsups.jar -u $FTP_USER:$FTP_PASSWORD ftp://193.31.26.152
