spring:
  datasource:
    url: jdbc:mysql://localhost/tsas_main?useLegacyDatetimeCode=false&serverTimezone=CET
    username: root
    password: Meycrosoft1337
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8092

  ssl:
    key-store-type: PKCS12
    key-store: keystore.p12
    key-store-password: Meycrosoft1337
    key-alias: tomcat