kafka-conf:
  bootstrapAddress: localhost:9092
  groupId: 1

kafka:
  consumer:
#    auto-offset-reset: earliest

spring:
  datasource:
    url: jdbc:mysql://localhost/tsas_main
    username: root
    password: Meycrosoft10
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8091