ts3api:
  queryName: TS3 Analytics Suite - New
  loginMessage: TS3 Analytics Suite connected
  serverIp: gr-esports.de
  serverQueryAdminName: serveradmin
  serverQueryAdminPassword: Meycrosoft1337
  serverId: 2
  afkChannels: 92,93
  locationInfoUpdateInterval: 3
  userInChannelInterval: 60

kafka:
  bootstrapAddress: localhost:9092

spring:
  datasource:
    url: jdbc:mysql://localhost/tsas_main?useLegacyDatetimeCode=false&serverTimezone=CET
    username: root
    password: Meycrosoft1337
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8090

  ssl:
    key-store-type: PKCS12
    key-store: keystore.p12
    key-store-password: Meycrosoft1337
    key-alias: tomcat