kafka:
  bootstrapAddress: localhost:9092
  groupId: 1

spring:
  datasource:
    url: jdbc:mysql://localhost/tsas_main
    username: root
    password: Meycrosoft10
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

#  kafka:
#    consumer:
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.weissdennis
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

server:
  port: 8091